/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.campaign.manager.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CampaignLocalization service. Represents a row in the &quot;CampaignLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.campaign.manager.model.impl.CampaignLocalizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.campaign.manager.model.impl.CampaignLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CampaignLocalization
 * @see com.liferay.campaign.manager.model.impl.CampaignLocalizationImpl
 * @see com.liferay.campaign.manager.model.impl.CampaignLocalizationModelImpl
 * @generated
 */
@ProviderType
public interface CampaignLocalizationModel extends BaseModel<CampaignLocalization> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a campaign localization model instance should use the {@link CampaignLocalization} interface instead.
	 */

	/**
	 * Returns the primary key of this campaign localization.
	 *
	 * @return the primary key of this campaign localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this campaign localization.
	 *
	 * @param primaryKey the primary key of this campaign localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the campaign localization ID of this campaign localization.
	 *
	 * @return the campaign localization ID of this campaign localization
	 */
	public long getCampaignLocalizationId();

	/**
	 * Sets the campaign localization ID of this campaign localization.
	 *
	 * @param campaignLocalizationId the campaign localization ID of this campaign localization
	 */
	public void setCampaignLocalizationId(long campaignLocalizationId);

	/**
	 * Returns the campaign ID of this campaign localization.
	 *
	 * @return the campaign ID of this campaign localization
	 */
	public long getCampaignId();

	/**
	 * Sets the campaign ID of this campaign localization.
	 *
	 * @param campaignId the campaign ID of this campaign localization
	 */
	public void setCampaignId(long campaignId);

	/**
	 * Returns the name of this campaign localization.
	 *
	 * @return the name of this campaign localization
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this campaign localization.
	 *
	 * @param name the name of this campaign localization
	 */
	public void setName(String name);

	/**
	 * Returns the description of this campaign localization.
	 *
	 * @return the description of this campaign localization
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this campaign localization.
	 *
	 * @param description the description of this campaign localization
	 */
	public void setDescription(String description);

	/**
	 * Returns the language ID of this campaign localization.
	 *
	 * @return the language ID of this campaign localization
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this campaign localization.
	 *
	 * @param languageId the language ID of this campaign localization
	 */
	public void setLanguageId(String languageId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CampaignLocalization campaignLocalization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CampaignLocalization> toCacheModel();

	@Override
	public CampaignLocalization toEscapedModel();

	@Override
	public CampaignLocalization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}